# Filename:    mesonet_config.yml
# Author:      Deanna Nash, dlnash@ucsb.edu
# Description: Dictionary of different download precipitation variables for mesonet stations


---

test:
    start: '201808010000'
    end:   '201808070000'
    vars: 'air_temp'
    obstimezone: 'UTC'
    stids: 'KSEA'
    units: 'temp|F'
    token: "6f7bc78232734beab9da77235a2bd351"
    
casejan2018:
    start: '201808010000'
    end:   '201808070000'
    obtimezone: 'UTC'
    stids: 'PAYA'
    token: "6f7bc78232734beab9da77235a2bd351"
    
casedec2020:
    start: '202011280000'
    end:   '202012040000'
    obtimezone: 'UTC'
    stids: 'PAYA'
    token: "6f7bc78232734beab9da77235a2bd351"
        
    
        
stationids:
    klukwan: ['QCHWC', 'CKTA2', 'SPCA2', 'DWSA2', 'TYAA2']
    klukwan_name: ['Chillkat FAA Web', 'Chillkat River Near', 'Sheep Camp', 'Dyea', 'Taiya River Near S']

    skagway: ['PAGY', 'SKTA2', 'SKXA2', 'EROWC', 'BEBE2', 'LIXA2']
    skagway_name: ['Skagway', 'Skagway Airport', 'Skagway WX', 'Eldred Rock FAA We', 'Berners Bay', 'Little Island']
        
    haines: ['PAHN', 'HAXA2']
    haines_name: ['Haines Airport', 'Haines']
        
    yakutat: ['YATA2', 'PAYA', 'YUTA2']
    yakutat_name: ['Yakutat', 'Yakutat Airport', 'USCRN Site at TONG']
        
    craig: ['CRGA2']
    craig_name: ['Craig']
        
    kasaan: ['KXAWC']
    kasaan_name: ['Kasan FAA Web']
        
    hoonah: ['HONA2', 'TKEWC', 'TKEA2']
    hoonah_name: ['Hoonah', 'Site TKEWC', 'Tenakee Springs']
    
...
