name: cenv
channels:
  - conda-forge
  - defaults  
dependencies:
  - python
  - pip
  - jupyterlab>=3.0
  - distributed
  - jupyter-resource-usage
  - jupyter-server-proxy
  - nb_conda_kernels
  - nco
  - nodejs
  - ipywidgets

  - pip:
      - dask-labextension
      - npm
