name: SEAK-clim
channels:
  - conda-forge
  - defaults  
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - netcdf4
  - xarray
  - cartopy
  - cmocean
  - seaborn
  - cmocean
  - ipykernel
  - geopandas
  - pyyaml
  - dask
  - metpy
  - xoak
  - odc-geo
  - cfgrib
  - pynio
  
  - pip:
    - rasterio
    - rioxarray==0.3.1
    - earthpy


