name: SEAK-clim
channels:
  - conda-forge
  - defaults  
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - netcdf4
  - xarray
  - cartopy
  - cmocean
  - seaborn
  - cmocean
  - ipykernel
  - geopandas
  - pyyaml
  - wrf-python
  - dask
  
  - pip:
    - boto3
    - botocore


